r"""The contrast-matrix checker must fail on every corruption it exists to catch.

Its first version passed six of seven mutations, which is worse than having no checker: a green
result on a corrupted table is what a reader trusts. Its second version still passed eight of
twenty-two, because it collected anything in the section that looked like a table row instead of
reading the rows inside the tabular.

A third failure mode arrived with the reporting-policy change that deleted the Holm column, the
verdict column, and the family table. The required-file check and the statistics-section check were
incidental effects of looping over prose patterns, so removing the patterns would have made
``check()`` return 0 for an empty paper directory and for a paper whose section label had been
deleted. ``test_an_empty_paper_directory_fails`` and ``test_a_removed_statistics_label_fails`` are
that case, and they are the two tests a naive deletion turns green.

These tests run the command line rather than calling ``check()``, so the exit status and an empty
stderr are what gets asserted: a finding printed on stdout with status 1 is a report, and a
traceback on stderr is a crash. They pin no number from the shipped record. The fixture paper is
built from what the tool itself emits, so regenerating the results moves the fixture with them, and
each corruption is described by its shape rather than by the value it damages.
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
TOOL = ROOT / "tools" / "emit_stats_table.py"

sys.path.insert(0, str(ROOT / "tools"))

import emit_stats_table as est  # noqa: E402


def _env(**overrides):
    """A clean environment, so an ambient CATCHBENCH_PAPER_DIR cannot steer these runs."""
    env = dict(os.environ)
    env.pop("CATCHBENCH_PAPER_DIR", None)
    env.update(overrides)
    return env


def _run(*args, env=None):
    return subprocess.run([sys.executable, str(TOOL), *args],
                          capture_output=True, text=True, env=env or _env())


def _check(paper):
    return _run("--check", "--paper", str(paper))


# --- the fixture paper, generated by the tool it checks ------------------------------------------

APPENDIX_TEMPLATE = """\
\\section{Comparison Groups and Ordering Tests}
\\label{app:stats}

Prose the statistics section carries, between its label and the matrix it introduces.

%(contrasts)s

\\section{Something Else}
Total & 1187 & configurations in the PRE corpus. \\\\
"""


@pytest.fixture(scope="module")
def block():
    """What ``--contrasts`` emits, which is also what ``--check`` compares the paper against."""
    done = _run("--contrasts")
    assert done.returncode == 0, done.stderr
    assert done.stderr == ""
    return done.stdout.replace("\r\n", "\n").rstrip("\n")


@pytest.fixture
def paper(tmp_path, block):
    """A minimal current paper. Each test mutates one thing and expects the check to fail."""
    (tmp_path / "09_appendix.tex").write_text(
        APPENDIX_TEMPLATE % {"contrasts": block}, encoding="utf-8")
    return tmp_path


def _read(paper):
    return (paper / "09_appendix.tex").read_text(encoding="utf-8")


def _write(paper, text):
    (paper / "09_appendix.tex").write_text(text, encoding="utf-8")


def _edit(paper, old, new, count=-1):
    text = _read(paper)
    assert old in text, f"fixture does not contain {old!r}; the test, not the tool, is wrong"
    _write(paper, text.replace(old, new) if count < 0 else text.replace(old, new, count))


def _data_rows(block_text):
    """The contrast rows, found by shape so that no test has to name a claim or a value."""
    rows = [line for line in block_text.splitlines()
            if line.endswith(r"\\") and " & " in line
            and not line.startswith(("Contrast ", r"\multicolumn", r"\caption"))]
    assert rows, "the generated block carries no contrast rows"
    return rows


def _caption_line(block_text):
    captions = [line for line in block_text.splitlines() if line.startswith(r"\caption{")]
    assert len(captions) == 1, "expected exactly one caption line in the generated block"
    return captions[0]


# --- the current paper, and the two cases a naive deletion turns green ---------------------------


def test_the_current_paper_passes(paper):
    done = _check(paper)
    assert done.returncode == 0, done.stdout
    assert "paper is current" in done.stdout
    assert done.stderr == ""


def test_an_empty_paper_directory_fails(tmp_path):
    """The trap. With no prose patterns left, a loop-shaped checker returns 0 here."""
    done = _check(tmp_path)
    assert done.returncode == 1
    assert "09_appendix.tex: missing" in done.stdout
    assert done.stderr == ""


def test_a_removed_statistics_label_fails(paper):
    """The other trap: the section boundary must be checked outside any pattern loop."""
    _edit(paper, "\\label{app:stats}\n", "")
    done = _check(paper)
    assert done.returncode == 1
    assert r"missing marker \label{app:stats}" in done.stdout
    assert done.stderr == ""


def test_a_commented_out_statistics_label_fails(paper):
    """A marker behind a percent sign is not a marker; a substring search accepted it."""
    _edit(paper, "\\label{app:stats}", "% \\label{app:stats}")
    done = _check(paper)
    assert done.returncode == 1
    assert r"missing marker \label{app:stats}" in done.stdout
    assert done.stderr == ""


def test_a_statistics_label_carrying_trailing_content_is_not_a_marker(paper):
    _edit(paper, "\\label{app:stats}", "\\label{app:stats} % and a note")
    done = _check(paper)
    assert done.returncode == 1
    assert r"missing marker \label{app:stats}" in done.stdout
    assert done.stderr == ""


def test_hidden_statistics_content_fails(paper):
    """A TeX conditional is not a comment, so a regex over the prose would not see it."""
    _edit(paper, "Prose the statistics section carries",
          "\\iffalse\nProse the statistics section carries")
    done = _check(paper)
    assert done.returncode == 1
    assert "a TeX conditional hides part of the statistics section" in done.stdout
    assert done.stderr == ""


# --- the block itself, compared byte for byte ----------------------------------------------------


def test_a_changed_cell_fails(paper, block):
    row = _data_rows(block)[0]
    damaged = re.sub(r"\d\.\d{3}", "9.999", row, count=1)
    assert damaged != row, "the mutation did not change the row"
    _edit(paper, row, damaged)
    done = _check(paper)
    assert done.returncode == 1
    assert "the contrast matrix differs from the generated block" in done.stdout
    assert "first difference at block line" in done.stdout
    assert done.stderr == ""


def test_a_missing_row_fails(paper, block):
    _edit(paper, _data_rows(block)[0] + "\n", "")
    done = _check(paper)
    assert done.returncode == 1
    assert "the contrast matrix differs from the generated block" in done.stdout
    assert done.stderr == ""


def test_a_duplicated_row_fails(paper, block):
    row = _data_rows(block)[0]
    _edit(paper, row + "\n", row + "\n" + row + "\n")
    done = _check(paper)
    assert done.returncode == 1
    assert "the contrast matrix differs from the generated block" in done.stdout
    assert done.stderr == ""


def test_reordered_rows_fail(paper, block):
    """Order carries meaning: the table is read alongside the module's declaration order."""
    first, second = _data_rows(block)[:2]
    text = _read(paper)
    _write(paper, text.replace(first, "PLACEHOLDER").replace(second, first)
           .replace("PLACEHOLDER", second))
    done = _check(paper)
    assert done.returncode == 1
    assert "the contrast matrix differs from the generated block" in done.stdout
    assert done.stderr == ""


def test_a_reindented_row_fails(paper, block):
    """The block is generated whole, so whitespace inside it is staleness rather than style."""
    row = _data_rows(block)[0]
    _edit(paper, row, "    " + row)
    done = _check(paper)
    assert done.returncode == 1
    assert done.stderr == ""


def test_a_changed_caption_fails(paper, block):
    caption = _caption_line(block)
    _edit(paper, caption,
          caption.replace(r"}\label{tab:all-contrasts}", r" An added sentence.}"
                          r"\label{tab:all-contrasts}"))
    done = _check(paper)
    assert done.returncode == 1
    assert "the contrast matrix differs from the generated block" in done.stdout
    assert done.stderr == ""


def test_a_changed_group_header_fails(paper, block):
    header = next(line for line in block.splitlines() if line.startswith(r"\multicolumn")
                  and r"\texttt{" in line)
    _edit(paper, header, header.replace(r"$\cdot$", r"$\cdot$ rewritten $\cdot$", 1))
    done = _check(paper)
    assert done.returncode == 1
    assert "the contrast matrix differs from the generated block" in done.stdout
    assert done.stderr == ""


# --- the sentinels that bound the block ----------------------------------------------------------


def test_a_commented_out_begin_sentinel_fails(paper):
    _edit(paper, est._CONTRASTS_BEGIN, "% " + est._CONTRASTS_BEGIN)
    done = _check(paper)
    assert done.returncode == 1
    assert "appears 0 times, expected once" in done.stdout
    assert done.stderr == ""


def test_a_deleted_end_sentinel_fails(paper):
    _edit(paper, est._CONTRASTS_END + "\n", "")
    done = _check(paper)
    assert done.returncode == 1
    assert "appears 0 times, expected once" in done.stdout
    assert done.stderr == ""


def test_a_duplicated_sentinel_fails(paper):
    _edit(paper, est._CONTRASTS_BEGIN, est._CONTRASTS_BEGIN + "\n" + est._CONTRASTS_BEGIN, count=1)
    done = _check(paper)
    assert done.returncode == 1
    assert "appears 2 times, expected once" in done.stdout
    assert done.stderr == ""


def test_sentinels_in_the_wrong_order_fail(paper, block):
    """Each sentinel appears once and the span is inverted, so the count check does not catch it."""
    lines = block.splitlines()
    assert lines[0] == est._CONTRASTS_BEGIN and lines[-1] == est._CONTRASTS_END
    inverted = "\n".join([lines[-1]] + lines[1:-1] + [lines[0]])
    _write(paper, APPENDIX_TEMPLATE % {"contrasts": inverted})
    done = _check(paper)
    assert done.returncode == 1
    assert "end marker precedes its begin marker" in done.stdout
    assert done.stderr == ""


def test_a_missing_block_fails(paper):
    text = _read(paper)
    _write(paper, text[:text.index(est._CONTRASTS_BEGIN)])
    done = _check(paper)
    assert done.returncode == 1
    assert done.stderr == ""


def test_an_unrelated_total_row_outside_the_block_is_ignored(paper):
    """The PRE corpus table's ``Total & 1187`` sits outside the block and must not be read."""
    assert "Total & 1187" in _read(paper)
    assert _check(paper).returncode == 0


# --- the command line surface --------------------------------------------------------------------


def test_the_default_mode_emits_the_block(block):
    done = _run()
    assert done.returncode == 0
    assert done.stderr == ""
    assert done.stdout.replace("\r\n", "\n").rstrip("\n") == block


def test_check_without_a_paper_directory_refuses(tmp_path):
    done = _run("--check")
    assert done.returncode != 0
    assert "--check needs --paper" in done.stderr


def test_the_paper_directory_can_come_from_the_environment(paper):
    done = _run("--check", env=_env(CATCHBENCH_PAPER_DIR=str(paper)))
    assert done.returncode == 0, done.stdout
    assert done.stderr == ""


def test_shipped_results_match_configured_paper():
    """Cross-repository closure, opt-in.

    Discovering a sibling checkout by relative path made the unit suite depend on this
    workstation's layout and on the paper repository's branch state. The environment variable is
    the same one the CLI already honors.
    """
    configured = os.environ.get("CATCHBENCH_PAPER_DIR")
    if not configured:
        pytest.skip("set CATCHBENCH_PAPER_DIR to run the cross-repository integration check")
    done = _run("--check", "--paper", configured, env=dict(os.environ))
    assert done.returncode == 0, done.stdout


# --- what the generated block says, and what it no longer says -------------------------------------
#
# These call the generator directly with synthetic records, because no command-line flag substitutes
# a results file and the cases below are about records the shipped file does not contain.


def _claim(group, index, metric="f1", method="paired percentile bootstrap",
           axis="run-level sampling"):
    """One synthetic contrast carrying every field the matrix prints, and nothing more.

    There is deliberately no ``verdict`` and no ``test`` key. The generator stopped reading both
    when the Holm column and the verdict column were deleted, so a record without them must still
    render; reintroducing either column turns every test in this section red at once.
    """
    return {
        "id": "%s.case%d" % (group, index),
        "family": group,
        "label": "%s: entrant %d vs floor" % (group, index),
        "metric": metric,
        "estimate": {"a": 0.5 + index / 100, "b": 0.4, "a_name": "entrant %d" % index,
                     "b_name": "floor", "difference_a_minus_b": 0.1 + index / 100},
        "interval": {"low": 0.01, "high": 0.2, "level": 0.95, "method": method, "axis": axis},
    }


DATA = {
    "claims": (
        [_claim("alpha_group", i) for i in range(3)]
        + [_claim("beta_group", i) for i in range(2)]
    ),
    "comparison_families": [
        {"id": "alpha_group", "size": 3, "description": "Three alpha contrasts."},
        {"id": "beta_group", "size": 2, "description": "Two beta contrasts."},
    ],
}

CLUSTERED = "task-clustered stratified percentile bootstrap"


def test_every_claim_appears_in_the_generated_block():
    generated = est.contrasts(DATA)
    for claim in DATA["claims"]:
        assert est._tex(claim["label"]) in generated, claim["id"]


def test_the_block_prints_no_adjusted_p_and_no_verdict():
    """The reporting-policy change, pinned where it would regress: the two deleted columns."""
    generated = est.contrasts(DATA)
    for word in ("Holm", "Verdict", "separates", "unresolved"):
        assert word not in generated, word


def test_the_column_count_agrees_across_the_preamble_header_and_rules(block):
    """Deleting a column leaves three places to update, and a stale one breaks the table."""
    lines = block.splitlines()
    preamble = next(line for line in lines if line.startswith(r"\begin{longtable}"))
    spec = preamble[preamble.index("{", len(r"\begin{longtable")) + 1:preamble.rindex("}")]
    spec = re.sub(r">\{[^}]*\}", "", spec).replace("@{}", "")
    assert len(re.findall(r"p\{[^}]*\}|[lcr]", spec)) == est._COLUMNS, spec
    header = next(line for line in lines if line.startswith("Contrast "))
    assert header.count("&") == est._COLUMNS - 1, header
    rules = [line for line in lines if line.startswith(r"\multicolumn")]
    assert rules and all(r"\multicolumn{%d}" % est._COLUMNS in line for line in rules)
    for row in _data_rows(block):
        assert row.count("&") == est._COLUMNS - 1, row


def test_a_group_header_states_scope_metric_and_construction():
    generated = est.contrasts(DATA)
    rule = r"\multicolumn{%d}{@{}p{%s}@{}}" % (est._COLUMNS, est._HEADER_RULE)
    assert (rule + r"{\texttt{alpha\_group} $\cdot$ Three alpha contrasts. $\cdot$ f1 $\cdot$ "
            r"paired percentile bootstrap, run-level sampling}\\" in generated)


def test_a_single_construction_group_leaves_its_rows_unannotated():
    generated = est.contrasts(DATA)
    assert "interval:" not in generated
    assert r"alpha\_group: entrant 0 vs floor & 0.500" in generated


def test_a_group_mixing_interval_constructions_names_it_on_every_row():
    """post_detection_auc is this shape: two task-clustered rows among five run-level ones.

    A header naming one construction over rows built two ways is a false statement in the paper,
    so the header defers and each row says which construction produced its interval.
    """
    claims = [_claim("mixed_group", 0),
              _claim("mixed_group", 1, method=CLUSTERED, axis="task-cluster resampling"),
              _claim("mixed_group", 2)]
    data = {"claims": claims,
            "comparison_families": [{"id": "mixed_group", "size": 3, "description": "Mixed."}]}
    generated = est.contrasts(data)
    assert "interval construction on each row" in generated
    assert "(interval: paired percentile bootstrap, run-level sampling)" in generated
    assert "(interval: %s, task-cluster resampling)" % CLUSTERED in generated
    for claim in claims:
        assert "%s (interval:" % est._tex(claim["label"]) in generated


def test_a_group_with_several_metrics_names_the_metric_on_each_row():
    """Three rows reading the same pair with three different numbers would name nothing."""
    claims = [_claim("mixed_family", i, metric=m)
              for i, m in enumerate(("top1", "top3", "mrr"))]
    for claim in claims:
        claim["label"] = "exec-rank vs position"
    data = {"claims": claims,
            "comparison_families": [{"id": "mixed_family", "size": 3, "description": "Mixed."}]}
    generated = est.contrasts(data)
    for metric in ("top1", "top3", "mrr"):
        assert "exec-rank vs position (%s)" % metric in generated
    assert "metric on each row" in generated


def test_a_group_mixing_both_names_both_on_the_row():
    claims = [_claim("both_group", 0, metric="top1"),
              _claim("both_group", 1, metric="mrr", method=CLUSTERED,
                     axis="task-cluster resampling")]
    data = {"claims": claims,
            "comparison_families": [{"id": "both_group", "size": 2, "description": "Both."}]}
    generated = est.contrasts(data)
    assert "(top1; interval: paired percentile bootstrap, run-level sampling)" in generated
    assert "(mrr; interval: %s, task-cluster resampling)" % CLUSTERED in generated


def test_a_group_whose_declared_size_disagrees_refuses_to_render():
    """A group that declares three contrasts and carries two must not print a short table."""
    data = {"claims": [_claim("alpha_group", 0)],
            "comparison_families": [{"id": "alpha_group", "size": 3, "description": "Three."}]}
    with pytest.raises(SystemExit, match="declares 3 contrasts"):
        est.contrasts(data)


def test_a_group_with_no_claims_refuses_to_render():
    data = {"claims": [],
            "comparison_families": [{"id": "ghost_group", "size": 0, "description": "None."}]}
    with pytest.raises(SystemExit, match="carry none"):
        est.contrasts(data)


def test_a_claim_whose_group_is_not_declared_refuses_to_render():
    """The table is the printed home of every claim, so a claim with no home is not a short table."""
    data = {"claims": [_claim("alpha_group", 0), _claim("orphan_group", 0)],
            "comparison_families": [{"id": "alpha_group", "size": 1, "description": "One."}]}
    with pytest.raises(SystemExit, match="no printed home"):
        est.contrasts(data)


def test_a_label_needing_unhandled_escaping_refuses_to_render():
    """Guessing at a backslash or a brace would emit a row that compiles into something else."""
    claim = _claim("alpha_group", 0)
    claim["label"] = r"entrant \textbf{x} vs floor"
    data = {"claims": [claim],
            "comparison_families": [{"id": "alpha_group", "size": 1, "description": "One."}]}
    with pytest.raises(SystemExit, match="needs escaping"):
        est.contrasts(data)


def test_ampersand_and_percent_in_a_label_are_escaped():
    claim = _claim("alpha_group", 0)
    claim["label"] = "Who&When 25% vs floor"
    data = {"claims": [claim],
            "comparison_families": [{"id": "alpha_group", "size": 1, "description": "One."}]}
    assert r"Who\&When 25\% vs floor" in est.contrasts(data)


def test_an_unsafe_group_id_refuses_to_render():
    broken = json.loads(json.dumps(DATA))
    broken["comparison_families"][0]["id"] = "alpha{group}"
    broken["claims"] = [dict(claim, family="alpha{group}") if claim["family"] == "alpha_group"
                        else claim for claim in broken["claims"]]
    with pytest.raises(SystemExit, match="needs escaping"):
        est.contrasts(broken)


def test_no_generated_line_carries_a_literal_tab():
    r"""A mangled backslash turns \times into a tab and prints ``imes`` in the PDF."""
    assert "\t" not in est.contrasts(DATA)


def test_the_group_header_uses_no_bar_character():
    """A bare | is an em dash under OT1, which is both wrong here and a dash the style forbids."""
    assert "|" not in est.contrasts(DATA)


def test_the_inventory_counts_records_not_distinct_ids():
    """Two groups that share an id are still two groups in the printed inventory."""
    data = {"claims": [{}] * 4,
            "comparison_families": [{"id": "same_id", "size": 2, "description": "First."},
                                    {"id": "same_id", "size": 2, "description": "Second."}]}
    assert est.inventory(data) == {"groups": 2, "contrasts": 4}
